name: 'Action common'
author: 'emirdeliz'
branding:
  icon: 'terminal'
  color: 'gray-dark'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
        cache: yarn
    - run: |
        yarn install
      shell: sh
