runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
        cache: yarn
    - run: |
        ssh-keyscan -H git@github.com/emirdeliz/barcode-reader-zbar-c.git >> ~/.ssh/known_hosts
        yarn install
      shell: sh
